# Ushahidi platform code dev container
# Used to mount code from the host machine

FROM dockerfile/ubuntu
MAINTAINER Robbie Mackay <robbie@ushahidi.com>

RUN mkdir -p /data
VOLUME ["/data"]

CMD ["true"]
