# Ushahidi platform php code container (development)
FROM dockerfile/ubuntu
MAINTAINER Robbie Mackay <robbie@ushahidi.com>

RUN mkdir -p /data
VOLUME ["/data"]

RUN mkdir -p /data/application/media/uploads
VOLUME ["/data/application/media/uploads

CMD ["true"]
